services:
  recipper-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
