# Generated by Django 5.0.6 on 2025-07-30 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='レシピ名')),
                ('ingredients', models.TextField(verbose_name='材料')),
                ('instructions', models.TextField(verbose_name='作り方')),
                ('cooking_time', models.IntegerField(blank=True, null=True, verbose_name='調理時間（分）')),
                ('servings', models.IntegerField(blank=True, null=True, verbose_name='何人分')),
                ('difficulty', models.CharField(choices=[('easy', '簡単'), ('medium', '普通'), ('hard', '難しい')], default='medium', max_length=20, verbose_name='難易度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI生成レシピ')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ',
                'ordering': ['-created_at'],
            },
        ),
    ]
